---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "charts-server"
  namespace: "kube-repo"
  labels:
    name: "charts-server"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "charts-server"
  template:
    metadata:
      labels:
        name: "charts-server"
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
      - name: "charts-server"
        image: "bitnami/chartmuseum:0.13.1"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: STORAGE
          value: local
        - name: STORAGE_LOCAL_ROOTDIR
          value: /bitnami/data
        ports: 
        - containerPort: 8080
        volumeMounts:
        - name: "data"
          mountPath: "/bitnami/data"
      volumes:
      - name: "data"
        hostPath:
          path: "/var/lib/doslab/charts"
---
apiVersion: v1
kind: Service
metadata:
  name: charts-server
  namespace: kube-system
  labels:
    name: charts-server
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: charts-server-port
    nodePort: 31004
  selector:
    name: charts-server
