---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: images.cloudplus.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.type
    name: TYPE
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  group: cloudplus.io
  names:
    kind: Image
    plural: images
    shortNames:
    - image
    singular: image
  scope: Namespaced
  version: v1alpha3
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: frontends.cloudplus.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.type
    name: TYPE
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  group: cloudplus.io
  names:
    kind: Frontend
    plural: frontends
    shortNames:
    - frontend
    singular: frontend
  scope: Namespaced
  version: v1alpha3
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cloudcontrollers.cloudplus.io
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  group: cloudplus.io
  names:
    kind: CloudController
    plural: cloudcontrollers
    shortNames:
    - ccs
    singular: cloudcontroller
  scope: Namespaced
  version: v1alpha3
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rbacroles.cloudplus.io
spec:
  additionalPrinterColumns:
  - JSONPath: ".metadata.creationTimestamp"
    name: AGE
    type: date
  group: cloudplus.io
  names:
    kind: RBACRole
    plural: rbacroles
    shortNames:
    - rbacrole
    singular: rbacrole
  scope: Namespaced
  version: v1alpha3
---
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rbacusers.cloudplus.io
spec:
  additionalPrinterColumns:
  - JSONPath: ".metadata.creationTimestamp"
    name: AGE
    type: date
  group: cloudplus.io
  names:
    kind: RBACUser
    plural: rbacusers
    shortNames:
    - rbacuser
    singular: rbacuser
  scope: Namespaced
  version: v1alpha3
